config/routes.rb
Rails.application.routes.draw do
  resources :listings
  resources :categories
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "listings#index"
  get "/payments/success", to: 'payments#success'
  post "/payments/webhook", to: 'payments#webhook'
  get "/users/profile", to: 'users#profile', as: 'profile'
  get "/search", to: 'listings#search', as: 'search'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :photo
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :login
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
  
    # Sanitization for parameters entered on sign up/sign in
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
      @category_listings = Listing.where("category_id = #{@category.id}")
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:category_name)
    end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: %i[ show edit update destroy ]

  # GET /listings or /listings.json
  def index
    @listings = Listing.all.reverse
  end

  # Search Listings Table using parameters from Search Bar
  def search  
    if params[:search].blank?  
      redirect_to(listings_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Listing.all.where("lower(listing_title) LIKE :search", search: "%#{@parameter}%")
    end  
  end

  # GET /listings/1 or /listings/1.json
  def show
    if user_signed_in?
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
          name: @listing.listing_title,
          description: @listing.listing_description,
          amount: @listing.price.to_i * 100,
          currency: 'aud',
          quantity: 1
        }],
        payment_intent_data: {
          metadata: {
            user_id: current_user.id,
            listing_id: @listing.id
          }
        },
        success_url: "#{root_url}payments/success?listing_id=#{@listing.id}", 
        cancel_url: "#{root_url}listings"
      )
    
    @session_id = session.id
  end
  end

  

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings or /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user = current_user
    @listing.photo.attach(params[:listing][:photo])
    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: "Listing was successfully created." }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1 or /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: "Listing was successfully updated." }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1 or /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: "Listing was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = current_user
    end

    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def listing_params
      params.require(:listing).permit(:listing_title, :listing_description, :user_id, :price, :condition, :category_id, :photo)
    end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
    skip_before_action :verify_authenticity_token, only: [:webhook]

    # Action for successful payment route
    def success
    end

    # Update listing status to "sold: true" when purchased.
    def webhook
        payment_id = params[:data][:object][:payment_intent]
        payment = Stripe::PaymentIntent.retrieve(payment_id)
        listing_id = payment.metadata.listing_id
        user_id = payment.metadata.user_id
    
        listing = Listing.find(listing_id.to_i)
        listing.sold = true
        listing.save
    
        status 200
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # Action for the Profile view to render for User
    def profile
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%# Category creation for admins only  %>

<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category_name %>
    <%= form.text_field :category_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%# Editing category for admin only %>
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<main class=" bg-gray-200 min-w-full flex  justify-center items-center flex-col">
  <h1 class="font-heading text-6xl text-red-600 m-5">Categories</h1>

    <%# Category cards grid %>
    <div class="flex flex-wrap justify-center min-w-full">
      <% @categories.each do |category| %>
        <%= link_to category.category_name, category_path(category.id), class: 'font-heading text-4xl p-10 bg-red-500 hover:bg-red-700 text-white text-2xl container shadow-md max-w-xs flex flex-col  m-10 justify-center items-center rounded-md' %>
      <% end %>
    </div>

  <br>
  <%# Show admin actions if user is an admin  %>
  <% if current_user.try(:admin?) %>
  <%= link_to 'New Category', new_category_path, class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>
  <% end %>
</main>

app/views/categories/new.html.erb
<%# Show New Category button for admins  %>

<% if current_user.admin? %>
    <h1>New Category</h1>

    <%= render 'form', category: @category %>

    <%= link_to 'Back', categories_path %>
    <%# Throw error if current user isn't an admin  %>
<% else %>
    <p>Only administrators may update categories.</p>
    <%= link_to 'Back', categories_path %>
<% end %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<main class=" bg-gray-200 min-w-full flex  items-center flex-col pb-10 min-h-screen">
  <%# Show current category name as heading  %>
  <h1 class="font-heading text-6xl text-red-600 m-5">
    <%= @category.category_name %>
  </h1>
  <%# Listing gallery %>
  <div class="flex flex-wrap justify-center min-w-full">
  <%# Generate card for each listing with this category  %>
  <% @category_listings.each do |listing| %>
        <div id="product-card" class="p-4 bg-white container shadow-md max-w-xs flex flex-col  m-10 justify-center items-center rounded-md max-h-96">
          <h3 class="text-lg font-semibold text-center"><%= listing.listing_title %></h3>
          <p>$<%= listing.price %></p>
          <%= image_tag listing.photo, class: "max-h-60" %>
          <%= link_to "View Item >", listing_path(listing.id), class: "rounded-xl bg-gray-700 text-white font-semibold hover:bg-gray-900 m-3 px-4 py-2" %>
        </div>
      <% end %>
  </div>

  <div id="links">
  <%# Allow editing category if user is an admin  %>
  <% if current_user.admin %>
  <%= link_to 'Edit', edit_category_path(@category), class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-lg text-white font-semibold shadow-lg hover:bg-red-900" %> 
  <% end %>
  <%= link_to 'Back', categories_path, class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-lg text-white font-semibold shadow-lg hover:bg-red-900" %>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RetroRocketRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>
  </head>

  <body>
    <%= render "shared/navbar" %>
      <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/listings/_form.html.erb
<%= form_with(model: listing, local: true) do |form| %>
  <% if listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
        <% listing.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div id="form-fields" class="flex flex-col pl-36" >
    <div class="field">
      <%= form.label :listing_title, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest" %><br>
      <%= form.text_field :listing_title, class: "border py-2 px-3 text-grey-darkest md:mr-2" %>
    </div>

    <div class="field">
      <%= form.label :listing_description, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest"  %><br>
      <%= form.text_area :listing_description %>
    </div>

    <div class="field">
      <%= form.label :price, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest"  %><br>
      <%= form.number_field :price %>
    </div>

    <div class="field">
      <%= form.label :condition, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest"  %><br>
      <%= form.select :condition, ["In Box", "New", "Used", "Damaged"] %>
    </div>

    <div class="field">
      <%= form.label :category_id, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest"  %><br>
      <%= form.collection_select :category_id, Category.all, :id, :category_name %>
    </div>

    <div class="field">
      <%= form.label :photo, class: "mb-2 uppercase tracking-wide font-bold text-lg text-grey-darkest"  %><br>
      <%= form.file_field :photo %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Listing', class: "m-5 px-2 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900"  %>
    </div>
    
  </div>

  
<% end %>

app/views/listings/edit.html.erb
<main class=" bg-gray-200 min-w-full flex   items-center flex-col pb-10">
<h1 class="font-heading text-6xl text-red-600 m-5">Editing Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: "m-5 px-2 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>

</main>

app/views/listings/index.html.erb
<p id="notice"><%= notice %></p>
<link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet"> 
<main class=" bg-gray-200 min-w-full flex  justify-center items-center flex-col">
  <h1 class="font-heading text-6xl text-red-600 m-5">All Items</h1>
  <%# Listings gallery  %>
  <div class="flex flex-wrap justify-center min-w-full">
    <%# Generate card for each listing  %>
    <% @listings.each do |listing| %>
      <div id="product-card" class="p-4 bg-white container shadow-md max-w-xs flex flex-col  m-10 justify-center items-center rounded-md max-h-96">
        <h3 class="text-lg font-semibold text-center"><%= listing.listing_title %></h3>
        <p>$<%= listing.price %></p>
        <%= image_tag listing.photo, class: "max-h-60" %>
        <%= link_to "View Item >", listing_path(listing.id), class: "rounded-xl bg-gray-700 text-white font-semibold hover:bg-gray-900 m-3 px-4 py-2" %>
      </div>
    <% end %>
  </div>
  
  <%# Allow new listings if user is signed in  %>
  <% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>
  <% end %>
</main>

app/views/listings/new.html.erb
<main class=" bg-gray-200 min-w-full flex   items-center flex-col pb-10">

<h1 class="font-heading text-6xl text-red-600 m-5">New Listing</h1>

<%= render 'form', listing: @listing %>

<%= link_to 'Back', listings_path, class: "m-5 px-2 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>

</main>

app/views/listings/search.html.erb
<main class=" bg-gray-200 min-w-full flex  justify-center items-center flex-col">

<h3 class="font-heading text-6xl text-red-600 m-5">Search Result</h3>  
<%# Listings gallery  %>
<div class="flex flex-wrap justify-center min-w-full">
<%# Generate card for each listing returned by search  %>
<% @results.each do |result| %>
      <div id="product-card" class="p-4 bg-white container shadow-md max-w-xs flex flex-col  m-10 justify-center items-center rounded-md">
        <h3 class="text-lg font-semibold text-center"><%= result.listing_title %></h3>
        <p>$<%= result.price %></p>
        <%= image_tag result.photo, class: "object-contain" %>
        <%= link_to "View Item >", listing_path(result.id), class: "rounded-xl bg-gray-700 text-white font-semibold hover:bg-gray-900 m-3 px-4 py-2" %>
      </div>
    <% end %>
  </div>

</main>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>
<main class=" bg-gray-200 min-w-full min-h-screen flex items-center flex-col ">
<%# List attributes for this listing  %>
<div id="listing-content" class="flex">
  <% if @listing.photo.attached? %>
  <p>
    <%= image_tag @listing.photo, class: "m-10 rounded-md shadow-lg" %>
  </p>
  <% end %>


<div id="product-info" class="flex flex-col flex-wrap m-10">
  <h1 class="text-2xl font-bold m-3">
    <%= @listing.listing_title %>
  </h1>

  <p class="text-xl font-bold text-red-500 m-3">
    $<%= @listing.price %>
  </p>

  <p class="m-3">
    <%= @listing.listing_description %>
  </p>

  <p class="m-3">
    <strong>Seller:</strong> <%= User.find(@listing.user_id).username %>
  </p>

  <p class="m-3">
    <strong>Condition:</strong>
    <%= @listing.condition %>
  </p>

  <p class="m-3">
    <strong>Category:</strong>
    <%= Category.find(@listing.category_id).category_name %>
  </p>

<%# Display a message if item has been sold already %>
  <% if (@listing.sold == true) %>
    <p>Item has been sold.</p>
  <% else %>
  <%# Create Buy Now button if user is signed in  %>
    <% if user_signed_in? %>
      <button data-stripe="payment", class= "m-5 px-2 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900">
        Buy Now
      </button> 
      <%# Redirect to sign up if user not logged in  %>
    <% else %>
      <%= button_to "Buy Now", new_user_registration_path, method: :get, class: "m-5 px-2 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>
    <% end %>
  <% end %>
</div>
</div>


<script src="https://js.stripe.com/v3/"></script>

<script>
  document
    .querySelector("[data-stripe='payment']")
    .addEventListener("click", () => {
      const stripe = Stripe(
        "<%= Rails.application.credentials.dig(:stripe, :public_key) %>"
      )

      stripe.redirectToCheckout({
        sessionId: "<%= @session_id %>"
      })
    })
</script>
 <hr class="text-black">

<div id="crud-links" class="flex">
<% if current_user == @listing.user %>
<%= link_to 'Edit', edit_listing_path(@listing), class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %> 
<%= link_to 'Delete', listing_path(@listing),
       method: :delete,
          data: { confirm: "Are you sure?" }, class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %> 
<% end %>
<%= link_to 'Back', listings_path, class: "m-5 px-4 py-2 bg-red-600 rounded-xl text-white font-semibold shadow-lg hover:bg-red-900" %>
</div>
</main>

app/views/payments/success.html.erb
<p>Payment Successful</p>
<%= link_to "Return", root_path %>

app/views/shared/_navbar.html.erb
<nav class="bg-gray-900 text-white flex justify-between items-center">
    <%# Show logo  %>
    <div id="logo" class="w-36">
        <%= image_tag("logo.png") %>
    </div>

    <%# Show search bar  %>
    <%= form_tag(search_path, :method => "get") do %> 
        <div class="flex lg:absolute">  
            <%= search_field_tag :search, params[:search], placeholder: "Search", class: "rounded-tl-lg rounded-bl-lg h-8 text-black" %>  
            <div class="input-group-btn">  
                <%= button_tag "Search", :class => 'bg-red-500 hover:bg-red-800 h-8 px-2 rounded-tr-lg rounded-br-lg',:name => nil%>  
            </div>  
        </div> 
    <% end %>


    <%# Show links  %>
    <div id="nav-links" class="flex p-4 space-x-3 text-xl">
        <%= link_to "Home", listings_path, class: "hover:text-red-500" %>
        <%= link_to "Categories", categories_path, class: "hover:text-red-500" %>
        
        <%# Conditional links for if user is signed in  %>
        <% if user_signed_in? %>
            <%# TODO: Add profile link %>
            <%= link_to "Create Listing", new_listing_path, class: "hover:text-red-500" %>
            <%= link_to "Profile", profile_path, class: "hover:text-red-500" %>
            <%= link_to "Sign Out", destroy_user_session_path, class: "hover:text-red-500", method: :delete%>
        <% else %>
            <%= link_to "Sign In", new_user_session_path, class: "hover:text-red-500" %>
                <p>|</p>
            <%= link_to "Sign Up", new_user_registration_path, class: "hover:text-red-500" %>
        <% end %>
    </div>

</nav>  

app/views/users/profile.html.erb
<div class=" bg-gray-200 min-w-full flex  justify-center items-center flex-col">

<%# Greet user by username  %>
<h1 class="text-4xl m-5"> Hey there, <%= current_user.username %>! </h1>

<h2 class="font-heading text-4xl text-red-600 m-5"> Your Current Listings </h2>

<%# Show the listings that have the current user listed as the seller  %>
<% user_listings = Listing.where(user_id: current_user.id, sold: false) %>
<div class="flex flex-wrap justify-center min-w-full">
    <% user_listings.each do |listing| %>
      <div id="product-card" class="p-4 bg-white container shadow-md max-w-xs flex flex-col  m-10 justify-center items-center rounded-md">
        <h3 class="text-lg font-semibold text-center"><%= listing.listing_title %></h3>
        <p>$<%= listing.price %></p>
        <%= image_tag listing.photo, class: "object-contain" %>
        <%= link_to "View Item >", listing_path(listing.id), class: "rounded-xl bg-gray-700 text-white font-semibold hover:bg-gray-900 m-3 px-4 py-2" %>
      </div>
    <% end %>
</div>
</div>